require("py.setup-plugins")
require("common.core.options")
require("py.core.options")
require("common.core.keymaps")
require("py.core.keymaps")
require("common.core.colorscheme")
require("common.plugins.undotree")
require("py.plugins.treesitter")
require("py.plugins.lspconfig")
require("py.plugins.ctag")
require("py.plugins.coverage")
require("py.plugins.autopairs")

