require("dart.plugins.init")
require("common.core.options")
require("dart.core.options")
require("common.core.keymaps")
require("dart.core.keymaps")
require("common.core.colorscheme")
require("common.plugins.undotree")
require("common.plugins.treesitter")({
  "dart",
  "json",
  "csv",
  "yaml"
})
require("common.plugins.lspconfig")({
  "yamlls",
  "jsonls",
  "dartls",
})
require("common.plugins.telescope")
require("common.plugins.trouble")
require("common.plugins.autopairs")

