require("go.plugins.init")
require("common.core.options")
require("go.core.options")
require("common.core.keymaps")
require("go.core.keymaps")
require("common.core.colorscheme")
require("common.plugins.undotree")
require("common.plugins.treesitter")({
  "go",
  "json",
  "csv",
  "yaml"
})
require("common.plugins.lspconfig")({
  "yamlls",
  "jsonls",
  "gopls",
})
require("common.plugins.telescope")
require("common.plugins.trouble")
require("common.plugins.autopairs")

